channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - omegaconf
  - numpy
  - pytorch::pytorch
  - llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision
  - einops
  - pytorch-lightning
  - torchmetrics
  - transformers
  - timm
  - wandb
  - pandas
  - scipy
  - openpyxl
  - nibabel
  - pydicom

  - pip
  - pip:
    - cytoolz
    - pynrrd
    - openmim # mim install mmcv
    - -e third-party/MONAI
