channels:
- conda-forge
- pytorch
- nvidia
- defaults
dependencies:
- python=3.11
- omegaconf
- numpy
- pytorch::pytorch=2.1.1
- llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
- pytorch::pytorch-cuda=11.8
- pytorch::torchvision
- einops
- lightning
- torchmetrics
- transformers
- timm
- wandb
- pandas
- scipy
- matplotlib
- openpyxl
- nibabel
- itk
- pydicom
- gdcm

- pip
- pip:
  - cytoolz
  - pynrrd
  - jsonargparse[signatures]
  - xformers
