channels:
- conda-forge
- pytorch
- nvidia
- defaults
dependencies:
- python=3.11
- omegaconf
- numpy
- pytorch::pytorch
- llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
- pytorch::pytorch-cuda=11.8
- pytorch::torchvision
- einops
- lightning
- pydantic<2  # https://github.com/Lightning-AI/lightning/issues/18027
- torchmetrics
- transformers
- timm
- wandb
- pandas
- scipy
- matplotlib
- openpyxl
- nibabel
- itk
- pydicom
- gdcm
- expect  # for unbuffer

- pip
- pip:
  - cytoolz
  - pynrrd
  - jsonargparse[signatures]  # for lightning CLI
