model: model.yaml
training:
  max_steps: 500000
optim_g:
- optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 3e-4
      weight_decay: 5e-2
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: ${training.max_steps}
        t_in_epochs: false
        warmup_t: 30000
        warmup_prefix: true
    interval: step
    frequency: 200
optim_d:
- optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-3
      weight_decay: 5e-2
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: ${training.max_steps}
        t_in_epochs: false
        warmup_t: 30000
        warmup_prefix: true
    interval: step
    frequency: 200
