vqvae:
  z_channels: 256
  embedding_dim: 256
  ed_kwargs:
    in_channels: 3
    z_channels: 256
    layer_channels: [128, 128, 256, 512]
    num_res_blocks: 2
    additional_interpolation: true
  vq_kwargs:
    num_embeddings: 8192
    embedding_dim: 256
    mode: soft
optimizer_g:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 5e-2
lr_scheduler_g:
  scheduler:
    class_path: timm.scheduler.CosineLRScheduler
    init_args:
      t_in_epochs: false
      lr_min: 1e-6
      warmup_t: 2000
      warmup_prefix: true
  interval: step
  frequency: 100
loss:
  quant_weight: 1e-6
  gan_weight: 1
  gan_start_step: 10000
  max_perceptual_slices: 16
optimizer_d:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 5e-2
lr_scheduler_d:
  scheduler:
    class_path: timm.scheduler.CosineLRScheduler
    init_args:
      t_in_epochs: false
      lr_min: 1e-6
      warmup_t: 2000
      warmup_prefix: true
  interval: step
  frequency: 100
data:
  dataset_weights:
    CheXpert: 0.03
    NIHChestX-ray: 0.03
    RSNA-2020-PED: 0.2
    RSNA-2022-CSFD: 0.5
  dl_conf:
    train_batch_size: 4
  trans_conf:
    train_tz: 3
    train_tx: 8
    train_scale_x: [0.75, 2.0]
training:
  max_steps: 200000
  ckpt_path: pre-trained/vqgan-gumbel-f8.ckpt
