vqvae: vqvae.yaml
optimizer_g:
  class_path: torch.optim.AdamW
  init_args:
    lr: 2e-5
    weight_decay: 5e-2
lr_scheduler_g:
  scheduler:
    class_path: timm.scheduler.CosineLRScheduler
    init_args:
      t_in_epochs: false
      lr_min: 1e-6
      warmup_t: 5000
      warmup_prefix: true
  interval: step
  frequency: 100
loss:
  quant_weight: 1e-7
  gan_weight: 6
  max_perceptual_slices: 24
optimizer_d:
  class_path: torch.optim.AdamW
  init_args:
    lr: 2e-4
    weight_decay: 5e-2
lr_scheduler_d:
  scheduler:
    class_path: timm.scheduler.CosineLRScheduler
    init_args:
      t_in_epochs: false
      lr_min: 1e-6
      warmup_t: 5000
      warmup_prefix: true
  interval: step
  frequency: 100
data: data.yaml
training:
  exp_name: tokenizer-continue
  seed: 233
  max_steps: 200000
  pretrained_ckpt_path: output/tokenizer/run-20230721_062106-3eyg9bv7/checkpoints/step=300000.ckpt
  disc_loss_momentum: 0.9
  use_gan_th: 0.035
