vqvae: vqvae.yaml
optimizer_g:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-5
    weight_decay: 5e-2
lr_scheduler_g:
  scheduler:
    class_path: timm.scheduler.CosineLRScheduler
    init_args:
      t_in_epochs: false
      lr_min: 1e-6
      warmup_t: 5000
      warmup_prefix: true
  interval: step
  frequency: 100
loss:
  quant_weight: 1e-7
  gan_weight: 1e-3
  adaptive_gan_weight: false
  max_perceptual_slices: 24
optimizer_d:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 5e-2
lr_scheduler_d:
  scheduler:
    class_path: timm.scheduler.CosineLRScheduler
    init_args:
      t_in_epochs: false
      lr_min: 1e-6
      warmup_t: 5000
      warmup_prefix: true
  interval: step
  frequency: 100
data: data.yaml
training:
  exp_name: tokenizer-gan
  seed: 777
  max_steps: 100000
  pretrained_ckpt_path: output/tokenizer/run-20230726_021033-zdffhgt5/checkpoints/step=200000.ckpt
  disc_loss_momentum: 0.9
  use_gan_th: 0.03
