class_path: pumit.model.ViTForMIM
init_args:
  patch_embed_grad_scale: 0.1
  pos_embed_shape: [5, 10, 10]
  pretrained_pos_embed_shape: [16, 16]
  mask_ratio: 0.55
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 2e-5
      weight_decay: 5e-2
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_in_epochs: false
        lr_min: 1e-6
        warmup_t: 10000
        warmup_prefix: true
    interval: step
    frequency: 100
