# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - requirements: docs/requirements.txt
